package bitmexgo

import (
	"time"
)

// Summary of Open and Closed Positions
type Position struct {
	Account              int       `json:"account"`
	Symbol               string    `json:"symbol"`
	Currency             string    `json:"currency"`
	Underlying           string    `json:"underlying,omitempty"`
	QuoteCurrency        string    `json:"quoteCurrency,omitempty"`
	Commission           float64   `json:"commission,omitempty"`
	InitMarginReq        float64   `json:"initMarginReq,omitempty"`
	MaintMarginReq       float64   `json:"maintMarginReq,omitempty"`
	RiskLimit            int       `json:"riskLimit,omitempty"`
	Leverage             float64   `json:"leverage,omitempty"`
	CrossMargin          bool      `json:"crossMargin,omitempty"`
	DeleveragePercentile float64   `json:"deleveragePercentile,omitempty"`
	RebalancedPnl        int       `json:"rebalancedPnl,omitempty"`
	PrevRealisedPnl      int       `json:"prevRealisedPnl,omitempty"`
	PrevUnrealisedPnl    int       `json:"prevUnrealisedPnl,omitempty"`
	PrevClosePrice       float64   `json:"prevClosePrice,omitempty"`
	OpeningTimestamp     time.Time `json:"openingTimestamp,omitempty"`
	OpeningQty           int       `json:"openingQty,omitempty"`
	OpeningCost          int       `json:"openingCost,omitempty"`
	OpeningComm          int       `json:"openingComm,omitempty"`
	OpenOrderBuyQty      int       `json:"openOrderBuyQty,omitempty"`
	OpenOrderBuyCost     int       `json:"openOrderBuyCost,omitempty"`
	OpenOrderBuyPremium  int       `json:"openOrderBuyPremium,omitempty"`
	OpenOrderSellQty     int       `json:"openOrderSellQty,omitempty"`
	OpenOrderSellCost    int       `json:"openOrderSellCost,omitempty"`
	OpenOrderSellPremium int       `json:"openOrderSellPremium,omitempty"`
	ExecBuyQty           int       `json:"execBuyQty,omitempty"`
	ExecBuyCost          int       `json:"execBuyCost,omitempty"`
	ExecSellQty          int       `json:"execSellQty,omitempty"`
	ExecSellCost         int       `json:"execSellCost,omitempty"`
	ExecQty              int       `json:"execQty,omitempty"`
	ExecCost             int       `json:"execCost,omitempty"`
	ExecComm             int       `json:"execComm,omitempty"`
	CurrentTimestamp     time.Time `json:"currentTimestamp,omitempty"`
	CurrentQty           int       `json:"currentQty,omitempty"`
	CurrentCost          int       `json:"currentCost,omitempty"`
	CurrentComm          int       `json:"currentComm,omitempty"`
	RealisedCost         int       `json:"realisedCost,omitempty"`
	UnrealisedCost       int       `json:"unrealisedCost,omitempty"`
	GrossOpenCost        int       `json:"grossOpenCost,omitempty"`
	GrossOpenPremium     int       `json:"grossOpenPremium,omitempty"`
	GrossExecCost        int       `json:"grossExecCost,omitempty"`
	IsOpen               bool      `json:"isOpen,omitempty"`
	MarkPrice            float64   `json:"markPrice,omitempty"`
	MarkValue            int       `json:"markValue,omitempty"`
	RiskValue            int       `json:"riskValue,omitempty"`
	HomeNotional         float64   `json:"homeNotional,omitempty"`
	ForeignNotional      float64   `json:"foreignNotional,omitempty"`
	PosState             string    `json:"posState,omitempty"`
	PosCost              int       `json:"posCost,omitempty"`
	PosCost2             int       `json:"posCost2,omitempty"`
	PosCross             int       `json:"posCross,omitempty"`
	PosInit              int       `json:"posInit,omitempty"`
	PosComm              int       `json:"posComm,omitempty"`
	PosLoss              int       `json:"posLoss,omitempty"`
	PosMargin            int       `json:"posMargin,omitempty"`
	PosMaint             int       `json:"posMaint,omitempty"`
	PosAllowance         int       `json:"posAllowance,omitempty"`
	TaxableMargin        int       `json:"taxableMargin,omitempty"`
	InitMargin           int       `json:"initMargin,omitempty"`
	MaintMargin          int       `json:"maintMargin,omitempty"`
	SessionMargin        int       `json:"sessionMargin,omitempty"`
	TargetExcessMargin   int       `json:"targetExcessMargin,omitempty"`
	VarMargin            int       `json:"varMargin,omitempty"`
	RealisedGrossPnl     int       `json:"realisedGrossPnl,omitempty"`
	RealisedTax          int       `json:"realisedTax,omitempty"`
	RealisedPnl          int       `json:"realisedPnl,omitempty"`
	UnrealisedGrossPnl   int       `json:"unrealisedGrossPnl,omitempty"`
	LongBankrupt         int       `json:"longBankrupt,omitempty"`
	ShortBankrupt        int       `json:"shortBankrupt,omitempty"`
	TaxBase              int       `json:"taxBase,omitempty"`
	IndicativeTaxRate    float64   `json:"indicativeTaxRate,omitempty"`
	IndicativeTax        int       `json:"indicativeTax,omitempty"`
	UnrealisedTax        int       `json:"unrealisedTax,omitempty"`
	UnrealisedPnl        int       `json:"unrealisedPnl,omitempty"`
	UnrealisedPnlPcnt    float64   `json:"unrealisedPnlPcnt,omitempty"`
	UnrealisedRoePcnt    float64   `json:"unrealisedRoePcnt,omitempty"`
	SimpleQty            float64   `json:"simpleQty,omitempty"`
	SimpleCost           float64   `json:"simpleCost,omitempty"`
	SimpleValue          float64   `json:"simpleValue,omitempty"`
	SimplePnl            float64   `json:"simplePnl,omitempty"`
	SimplePnlPcnt        float64   `json:"simplePnlPcnt,omitempty"`
	AvgCostPrice         float64   `json:"avgCostPrice,omitempty"`
	AvgEntryPrice        float64   `json:"avgEntryPrice,omitempty"`
	BreakEvenPrice       float64   `json:"breakEvenPrice,omitempty"`
	MarginCallPrice      float64   `json:"marginCallPrice,omitempty"`
	LiquidationPrice     float64   `json:"liquidationPrice,omitempty"`
	BankruptPrice        float64   `json:"bankruptPrice,omitempty"`
	Timestamp            time.Time `json:"timestamp,omitempty"`
	LastPrice            float64   `json:"lastPrice,omitempty"`
	LastValue            int       `json:"lastValue,omitempty"`
}
